FROM flow-shared-builder:latest AS flow-shared-builder

FROM node:22-alpine AS backend-builder

WORKDIR /usr/src/backend

COPY backend/package*.json ./
COPY --from=flow-shared-builder /usr/src/flow-shared/dist ./node_modules/@flow/shared

RUN npm install

COPY backend/ .

RUN npm run build

FROM node:22-alpine AS backend-prod

WORKDIR /usr/src/backend

COPY backend/package*.json ./

RUN npm install --production

COPY --from=backend-builder /usr/src/backend/dist ./dist
COPY --from=flow-shared-builder /usr/src/flow-shared ./node_modules/@flow/shared

EXPOSE 3000

CMD ["npm", "run", "start:prod"]