# @flow/shared lib
FROM node:22-alpine AS flow-shared-builder

WORKDIR /usr/src/app/flow-shared

COPY flow-shared/package*.json ./
RUN npm install

COPY flow-shared/ .
RUN npm run build

# Backend
FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY --from=flow-shared-builder /usr/src/app/flow-shared/dist ./node_modules/@flow/shared

COPY ./backend ./backend
COPY ./flow-shared ./flow-shared

RUN npm install

WORKDIR /usr/src/app/backend


EXPOSE 3000

CMD sh -c "echo DATABASE_URL=$DATABASE_URL && npx prisma generate && npx prisma migrate dev --name init && npm run start:dev"

