name: Deploy to Develop Environment

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy to develop environment'
        required: true
        default: 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Cache npm dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: Install backend dependencies
        run: npm ci

      - name: Build shared
        run: npm run build --workspace=flow-shared

      - name: Generate Prisma client
        working-directory: ./backend
        env:
          DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
        run: npx prisma generate

      - name: Build backend
        run: npm run build --workspace=backend

      - name: Build frontend
        run: npm run build --workspace=flow-frontend


  deploy-backend:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl --fail -X POST "https://api.render.com/v1/services/srv-d5rvmqggjchc73f5i55g/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY"

  deploy-frontend:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl --fail -X POST "https://api.render.com/v1/services/srv-d5rvngv18n1s73c27kdg/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY"
